# Generated by Django 3.2.12 on 2024-06-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changshaapp', '0002_declarant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('file', models.URLField(blank=True, max_length=255)),
                ('authState', models.CharField(max_length=255)),
                ('authCode', models.CharField(max_length=255)),
            ],
        ),
    ]
