# Generated by Django 3.2.12 on 2024-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changshaapp', '0003_authentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('declarationArea', models.CharField(max_length=255)),
                ('declarationElectricity', models.FloatField()),
                ('FMCapacity', models.FloatField()),
                ('electricityPrice', models.FloatField()),
                ('mileagePrice', models.FloatField()),
                ('capacityPrice', models.FloatField()),
                ('reviewState', models.CharField(max_length=255)),
            ],
        ),
    ]
