# Generated by Django 3.2.12 on 2024-07-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changshaapp', '0004_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationExtractionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('extractionStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
